appName: "gateway"
appEnv:
  REDIS_CONN_STRING: "redis://default:$(REDIS_PASSWORD)@gateway-redis-master:6379/"
  CARS_API_URL: "http://cars-service/api/v1"
  RENTAL_API_URL: "http://rental-service/api/v1"
  PAYMENT_API_URL: "http://payment-service/api/v1"
hasRedis: true
