apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -c -o=k8s convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: cars
  name: cars
spec:
  ports:
    - name: "8070"
      port: 8070
      targetPort: 8070
  selector:
    io.kompose.service: cars
