apiVersion: v1
data:
  10-create-table.sql: |+
    CREATE TABLE cars
    (
        id                  SERIAL PRIMARY KEY,
        car_uid             uuid UNIQUE NOT NULL,
        brand               VARCHAR(80) NOT NULL,
        model               VARCHAR(80) NOT NULL,
        registration_number VARCHAR(20) NOT NULL,
        power               INT,
        price               INT         NOT NULL,
        type                VARCHAR(20)
            CHECK (type IN ('SEDAN', 'SUV', 'MINIVAN', 'ROADSTER')),
        availability        BOOLEAN     NOT NULL
    );

  20-insert-test-data.sql: "INSERT INTO cars (car_uid, brand, model, registration_number, power, type, price, availability)\nVALUES (\n    '109b42f3-198d-4c89-9276-a7520a7120ab', \n    'Mercedes Benz', \n    'GLA 250', \n    'ЛО777Х799',\n    249,\n    'SEDAN',\n    3500,\n    TRUE\n);"
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: cars-postgres
  name: cars-postgres-cm1
