apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -c -o=k8s convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: payment
  name: payment
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8050
  selector:
    io.kompose.service: payment
