apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -c -o=k8s convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: rental
  name: rental
spec:
  ports:
    - name: "8060"
      port: 8060
      targetPort: 8060
  selector:
    io.kompose.service: rental
