apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    appName: {{ .Values.appName }} 
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      appName: {{ .Values.appName }} 
  template:
    metadata:
      labels:
        appName: {{ .Values.appName }} 
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.appImage }}
          ports:
          - containerPort: {{ .Values.appPort }}
          env:
          {{- if .Values.hasPostgresql }}
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef: 
                name: {{ .Values.appName }}-postgresql
                key: postgres-password
          {{- end}}
          {{- range $k, $v := .Values.appEnv }}
          - name: {{ $k }}
            value: {{ $v | quote }}
          {{- end }}
      imagePullSecrets:- name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: PG_PASS
        - name: {{ .Values.registryCredSecret }}
